#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/wiki/Commands

# 切换为平铺模式
cmd + ctrl + shift + alt - b : yabai -m space --layout bsp
# 切换为堆叠模式
cmd + ctrl + shift + alt - s : yabai -m space --layout stack
# 全屏
cmd + ctrl + shift + alt - f : yabai -m window --toggle zoom-fullscreen
# 旋转窗口布局
cmd + ctrl + shift + alt - r : yabai -m space --rotate 180

cmd + ctrl + shift + alt - 0 : yabai -m space --balance

# 在 stack 模式下通过方向键切换窗口
ctrl - down : yabai -m window --focus stack.next
ctrl - up : yabai -m window --focus stack.prev

cmd - left : yabai -m window --warp west
cmd - down : yabai -m window --warp south
cmd - up : yabai -m window --warp north 
cmd - right : yabai -m window --warp east 

# resize window
alt - left : yabai -m window --resize left:-50:0; yabai -m window --resize right:-50:0
alt - down : yabai -m window --resize bottom:0:50; yabai -m window --resize top:0:50
alt - up : yabai -m window --resize top:0:-50; yabai -m window --resize bottom:0:-50
alt - right : yabai -m window --resize right:50:0; yabai -m window --resize left:50:0

# focus window
alt + ctrl - h : yabai -m window --focus west
alt + ctrl - j : yabai -m window --focus south
alt + ctrl - k : yabai -m window --focus north
alt + ctrl - l : yabai -m window --focus east
# toggle float window
alt + ctrl - f : yabai -m window --toggle float --grid 10:8:1:1:6:8
# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
alt + ctrl - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}" && \
                  yabai -m space --layout bsp
# destroy space 
alt + ctrl - s : yabai -m space --destroy
# reboot Yabai
alt + ctrl - r : /usr/bin/env osascript <<< "display notification \"Yabai is reloading\" with title \"Yabai\""; \
                 launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

# space
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9

alt + ctrl - 1 : yabai -m window --space  1; yabai -m space --focus 1
alt + ctrl - 2 : yabai -m window --space  2; yabai -m space --focus 2
alt + ctrl - 3 : yabai -m window --space  3; yabai -m space --focus 3
alt + ctrl - 4 : yabai -m window --space  4; yabai -m space --focus 4
alt + ctrl - 5 : yabai -m window --space  5; yabai -m space --focus 5
alt + ctrl - 6 : yabai -m window --space  6; yabai -m space --focus 6
alt + ctrl - 7 : yabai -m window --space  7; yabai -m space --focus 7
alt + ctrl - 8 : yabai -m window --space  8; yabai -m space --focus 8
alt + ctrl - 9 : yabai -m window --space  9; yabai -m space --focus 9
